name: Tests

on: [push, pull_request]

jobs:
  x64-ubuntu:
    name: x64-ubuntu
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: |
            _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}

      - name: Install elan
        run: |
            curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover-community/lean:3.26.0 -y

      - name: Add Lean to PATH
        run: echo "$HOME/.elan/bin/" >> $GITHUB_PATH
        if: runner.os != 'Windows'

      - name: Install the Lean LSP
        run: sudo npm install -g lean-language-server

      - name: Install nvim dependencies
        run: |
          mkdir packpath
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig packpath/nvim-lspconfig
          git clone --depth 1 https://github.com/norcalli/snippets.nvim packpath/snippets.nvim
          git clone --depth 1 https://github.com/nvim-lua/completion-nvim packpath/completion-nvim
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim packpath/plenary.nvim

      - name: Run tests
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          make test
