name: Tests

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        lean-version:
          - "leanprover-community/lean:3.33.0"
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: |
            _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}

      - name: Install elan
        run: |
            curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain "${{ matrix.lean-version }}" -y
            echo "$HOME/.elan/bin/" >> $GITHUB_PATH
        if: runner.os == 'Linux'

      - name: Install neovim
        run: |
          neovim_dir=$HOME/neovim
          mkdir $neovim_dir
          curl -sL https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-linux64.tar.gz \
            | tar xzf - --strip-components=1 -C $neovim_dir
          echo $neovim_dir/bin >> $GITHUB_PATH
        if: runner.os == 'Linux'

      - name: Install neovim and elan
        run: |
          brew update
          brew install elan
          brew install --head neovim
          elan toolchain install "${{ matrix.lean-version }}"
          elan default "${{ matrix.lean-version }}"
        if: runner.os == 'macOS'

      - name: Install the Lean LSP
        run: sudo npm install -g lean-language-server
        if: contains(matrix.lean-version, 'lean:3')

      - name: Install nvim dependencies
        run: |
          mkdir packpath
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig packpath/nvim-lspconfig
          git clone --depth 1 https://github.com/norcalli/snippets.nvim packpath/snippets.nvim
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim packpath/plenary.nvim

      - name: Run tests
        run: |
          make test
        if: runner.os == 'Linux'

      - name: Run tests
        run: make test
        if: runner.os == 'macOS'
