name: Tests

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        nvim-version:
          - v0.5.0
          - v0.5.1
          - nightly
        lean-version:
          - "leanprover-community/lean:3.33.0"
    steps:
      - uses: actions/checkout@v2

      - name: Install macos dependencies
        run: |
          brew update
          brew install coreutils
        if: runner.os == 'macOS'

      - name: Install elan
        run: |
            curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain "${{ matrix.lean-version }}" -y
            echo "$HOME/.elan/bin/" >> $GITHUB_PATH

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1.2.8
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}

      - name: Install the Lean LSP
        run: sudo npm install -g lean-language-server
        if: contains(matrix.lean-version, 'lean:3')

      - name: Install nvim dependencies
        run: |
          mkdir packpath
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig packpath/nvim-lspconfig
          git clone --depth 1 https://github.com/norcalli/snippets.nvim packpath/snippets.nvim
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim packpath/plenary.nvim

      - name: Run tests
        run: make test
