name: Style checking

on: [push, pull_request]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
      - name: Lint
        run: make lint
