name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install luacheck
      run: |
        sudo apt-get update
        sudo apt-get install luarocks
        sudo luarocks install luacheck
        sudo chown -R $USER /home/runner/.cache
    - uses: pre-commit/action@v2.0.0
